version: "3.8"

services:
  postgres-container:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./docker/postgresDB:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tweetDB

